CREATE TABLE [dbo].[StudentCommitment] (
    [StudentCommitmentID]   INT            IDENTITY (1, 1) NOT NULL,
    [StudentID]             INT            NOT NULL,
    [AgencyID]              INT            NULL,
    [CommitmentTypeID]      INT            NULL,
    [AddressID]             INT            NULL,
    [SupervisorContactID]   INT            NULL,
    [MentorContactID]       INT            NULL,
    [SalaryTypeID]          INT            NULL,
    [Justification]         VARCHAR (1000) NULL,
    [StartDate]             DATE           NULL,
    [EndDate]               DATE           NULL,
    [JobSearchTypeID]       INT            NULL,
    [JobTitle]              VARCHAR (100)  NULL,
    [SalaryMinimum]         MONEY          NULL,
    [SalaryMaximum]         MONEY          NULL,
    [PayPlan]               VARCHAR (3)    NULL,
    [Series]                VARCHAR (5)    NULL,
    [Grade]                 VARCHAR (5)    NULL,
    [FinalJobOfferLetterID] INT            NULL,
    [PositionDescriptionID] INT            NULL,
    [TentativeOfferID]      INT            NULL,
    CONSTRAINT [PK_StudentCommitment] PRIMARY KEY CLUSTERED ([StudentCommitmentID] ASC),
    CONSTRAINT [FK_StudentCommitment_Address] FOREIGN KEY ([AddressID]) REFERENCES [dbo].[Address] ([AddressID]),
    CONSTRAINT [FK_StudentCommitment_Agency] FOREIGN KEY ([AgencyID]) REFERENCES [dbo].[Agency] ([AgencyID]),
    CONSTRAINT [FK_StudentCommitment_CommitmentType] FOREIGN KEY ([CommitmentTypeID]) REFERENCES [dbo].[CommitmentType] ([CommitmentTypeID]),
    CONSTRAINT [FK_StudentCommitment_ContactMentor] FOREIGN KEY ([MentorContactID]) REFERENCES [dbo].[Contact] ([ContactID]),
    CONSTRAINT [FK_StudentCommitment_ContactSupervisor] FOREIGN KEY ([SupervisorContactID]) REFERENCES [dbo].[Contact] ([ContactID]),
    CONSTRAINT [FK_StudentCommitment_SalaryType] FOREIGN KEY ([SalaryTypeID]) REFERENCES [dbo].[SalaryType] ([SalaryTypeID]),
    CONSTRAINT [FK_StudentCommitment_Student] FOREIGN KEY ([StudentID]) REFERENCES [dbo].[Student] ([StudentID]),
    CONSTRAINT [FK_StudentCommitment_StudentDocumentFinalOffer] FOREIGN KEY ([FinalJobOfferLetterID]) REFERENCES [dbo].[StudentDocument] ([StudentDocumentID]),
    CONSTRAINT [FK_StudentCommitment_StudentDocumentPositionDesc] FOREIGN KEY ([PositionDescriptionID]) REFERENCES [dbo].[StudentDocument] ([StudentDocumentID]),
    CONSTRAINT [FK_StudentCommitment_StudentDocumentTenative] FOREIGN KEY ([TentativeOfferID]) REFERENCES [dbo].[StudentDocument] ([StudentDocumentID])
);

